// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigData, MapConfigTableId } from "./tables/MapConfig.sol";
import { Match, MatchTableId } from "./tables/Match.sol";
import { PlayerOne, PlayerOneTableId } from "./tables/PlayerOne.sol";
import { PlayerTwo, PlayerTwoTableId } from "./tables/PlayerTwo.sol";
import { CurrentTurn, CurrentTurnTableId } from "./tables/CurrentTurn.sol";
import { CurrentPlayer, CurrentPlayerTableId } from "./tables/CurrentPlayer.sol";
import { CurrentMana, CurrentManaTableId } from "./tables/CurrentMana.sol";
import { PlacedCards, PlacedCardsData, PlacedCardsTableId } from "./tables/PlacedCards.sol";
import { Card, CardTableId } from "./tables/Card.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { UsedIn, UsedInTableId } from "./tables/UsedIn.sol";
import { IsBase, IsBaseTableId } from "./tables/IsBase.sol";
import { UnitType, UnitTypeTableId } from "./tables/UnitType.sol";
import { AttackDamage, AttackDamageTableId } from "./tables/AttackDamage.sol";
import { MaxHp, MaxHpTableId } from "./tables/MaxHp.sol";
import { CurrentHp, CurrentHpTableId } from "./tables/CurrentHp.sol";
import { MovementSpeed, MovementSpeedTableId } from "./tables/MovementSpeed.sol";
import { ActionReady, ActionReadyTableId } from "./tables/ActionReady.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
