// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum CardTypes {
  VaanStrife,
  Felguard,
  Sakura,
  Freya,
  Lyra,
  Madmartigan,
  Base
}
